/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminClonePolicyToggle: typeof import('./src/components/collaboration/AdminClonePolicyToggle.vue')['default']
    ApiPlaybook: typeof import('./src/components/velocity/ApiPlaybook.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    CloneProjectDialog: typeof import('./src/components/collaboration/CloneProjectDialog.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    FilterBar: typeof import('./src/components/projects/FilterBar.vue')['default']
    LoadingSkeleton: typeof import('./src/components/common/LoadingSkeleton.vue')['default']
    MapView: typeof import('./src/components/explore/MapView.vue')['default']
    ModuleDetailDialog: typeof import('./src/components/modules/ModuleDetailDialog.vue')['default']
    ProjectLockBanner: typeof import('./src/components/collaboration/ProjectLockBanner.vue')['default']
    ProjectMembersPanel: typeof import('./src/components/collaboration/ProjectMembersPanel.vue')['default']
    PwaInstallPrompt: typeof import('./src/components/pwa/PwaInstallPrompt.vue')['default']
    PwaUpdatePrompt: typeof import('./src/components/pwa/PwaUpdatePrompt.vue')['default']
    QuickStartGuide: typeof import('./src/components/velocity/QuickStartGuide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharePointBrowser: typeof import('./src/components/sharepoint/SharePointBrowser.vue')['default']
    SharePointPanel: typeof import('./src/components/sharepoint/SharePointPanel.vue')['default']
    SharePointStepArtifacts: typeof import('./src/components/sharepoint/SharePointStepArtifacts.vue')['default']
    ThemeSwitcher: typeof import('./src/components/layout/ThemeSwitcher.vue')['default']
    VersionsBadge: typeof import('./src/components/collaboration/VersionsBadge.vue')['default']
    VersionsPanel: typeof import('./src/components/collaboration/VersionsPanel.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
