/**
 * SharePoint Integration E2E Test
 *
 * Usage:
 *   npx tsx src/__tests__/services/sharepoint-e2e.test.ts
 *
 * Requires:
 *   - Server running on http://localhost:3000
 *   - Valid API key (set API_KEY env var or update below)
 *   - SharePoint credentials in .env (SHAREPOINT_APPLICATION_CLIENT_ID, etc.)
 */

const API_BASE = process.env.API_BASE || 'http://localhost:3000/api/v1';
const API_KEY = process.env.API_KEY || 'velo_98c8c5bc6ca33c6b4644d5c76bf1f44fc53d3ae1';

async function request(method: string, path: string, body?: unknown, isFormData = false): Promise<any> {
  const headers: Record<string, string> = {
    'X-API-Key': API_KEY,
  };
  if (!isFormData) {
    headers['Content-Type'] = 'application/json';
  }

  const options: RequestInit = { method, headers };
  if (body && !isFormData) {
    options.body = JSON.stringify(body);
  } else if (body && isFormData) {
    options.body = body as FormData;
  }

  const res = await fetch(`${API_BASE}${path}`, options);
  const text = await res.text();
  let data: any;
  try { data = JSON.parse(text); } catch { data = text; }

  if (!res.ok && res.status >= 400) {
    console.error(`  ❌ ${method} ${path} → ${res.status}:`, typeof data === 'object' ? JSON.stringify(data).substring(0, 200) : text.substring(0, 200));
  }

  return { status: res.status, data, ok: res.ok };
}

function assert(condition: boolean, message: string) {
  if (!condition) {
    console.error(`  ❌ ASSERTION FAILED: ${message}`);
    process.exitCode = 1;
  } else {
    console.log(`  ✓ ${message}`);
  }
}

async function main() {
  console.log('═══════════════════════════════════════════════════');
  console.log('SharePoint Integration E2E Test');
  console.log('═══════════════════════════════════════════════════\n');

  // ── 1. Connection Check ──
  console.log('1. Checking SharePoint connection...');
  const statusRes = await request('GET', '/sharepoint/status');
  console.log('   Status:', statusRes.status, statusRes.data?.data?.connected ? 'CONNECTED' : 'NOT CONNECTED');
  if (!statusRes.data?.data?.connected) {
    console.log('\n⚠️  SharePoint is not configured or not reachable.');
    console.log('   Set SHAREPOINT_APPLICATION_CLIENT_ID, SHAREPOINT_APPLICATION_CLIENT_SECRET,');
    console.log('   SHAREPOINT_APPLICATION_TENANT_ID, and SHAREPOINT_SITE_URL in .env');
    console.log('\n   Running remaining tests anyway (they will report errors)...\n');
  } else {
    console.log(`   Site: ${statusRes.data.data.siteName}`);
    console.log(`   Drive: ${statusRes.data.data.driveId}`);
  }

  // ── 2. Get a project to work with ──
  console.log('\n2. Finding a test project...');
  const projectsRes = await request('GET', '/projects?limit=1');
  if (!projectsRes.data?.data?.length) {
    console.error('   No projects found. Create a project first.');
    return;
  }
  const project = projectsRes.data.data[0];
  const projectId = project.pk_project || project.id;
  console.log(`   Project: ${project.project_name || project.name} (${projectId})`);

  // ── 3. Ensure project folder hierarchy ──
  console.log('\n3. Creating project folder hierarchy in SharePoint...');
  const foldersRes = await request('POST', `/sharepoint/projects/${projectId}/folders`);
  if (foldersRes.ok) {
    const data = foldersRes.data?.data;
    console.log(`   Folders created/found: ${data?.folders?.length || data?.created || 'unknown'}`);
    assert(foldersRes.status === 200 || foldersRes.status === 201, 'Folder hierarchy created');
  } else {
    console.log(`   Status: ${foldersRes.status} — ${JSON.stringify(foldersRes.data?.error || foldersRes.data).substring(0, 200)}`);
  }

  // ── 4. List project folders ──
  console.log('\n4. Listing tracked folders...');
  const listFoldersRes = await request('GET', `/sharepoint/projects/${projectId}/folders`);
  const folders = listFoldersRes.data?.data || [];
  console.log(`   Tracked folders: ${folders.length}`);
  if (folders.length > 0) {
    for (const f of folders.slice(0, 5)) {
      console.log(`     - [${f.folder_type}] ${f.sp_folder_path}`);
    }
    if (folders.length > 5) console.log(`     ... and ${folders.length - 5} more`);
  }

  // ── 5. Upload a test file ──
  let uploadedItemId: string | null = null;
  if (folders.length > 0) {
    const targetFolder = folders.find((f: any) => f.folder_type === 'project') || folders[0];
    console.log(`\n5. Uploading test file to folder: ${targetFolder.sp_folder_path}...`);

    // Create a simple text file as FormData
    const testContent = `# Test Document\n\nGenerated by Velo SharePoint E2E test.\nTimestamp: ${new Date().toISOString()}\n\nThis file verifies the SharePoint integration is working correctly.\n`;
    const blob = new Blob([testContent], { type: 'text/markdown' });

    const formData = new FormData();
    formData.append('file', blob, `velo-test-${Date.now()}.md`);

    const uploadRes = await fetch(`${API_BASE}/sharepoint/folders/${targetFolder.pk_sharepoint_folder}/files`, {
      method: 'POST',
      headers: { 'X-API-Key': API_KEY },
      body: formData,
    });
    const uploadData = await uploadRes.json().catch(() => null);

    if (uploadRes.ok && uploadData?.data) {
      uploadedItemId = uploadData.data.id;
      console.log(`   Uploaded: ${uploadData.data.name} (${uploadData.data.id})`);
      console.log(`   Web URL: ${uploadData.data.webUrl || 'N/A'}`);
      assert(true, 'File uploaded successfully');
    } else {
      console.log(`   Upload status: ${uploadRes.status}`);
      console.log(`   Response: ${JSON.stringify(uploadData).substring(0, 200)}`);
    }
  } else {
    console.log('\n5. Skipping file upload (no folders tracked)');
  }

  // ── 6. List files in folder ──
  if (folders.length > 0) {
    const targetFolder = folders.find((f: any) => f.folder_type === 'project') || folders[0];
    console.log(`\n6. Listing files in folder: ${targetFolder.sp_folder_path}...`);
    const filesRes = await request('GET', `/sharepoint/folders/${targetFolder.pk_sharepoint_folder}/files`);
    const files = filesRes.data?.data || [];
    console.log(`   Files: ${files.length}`);
    for (const f of files.slice(0, 5)) {
      const sizeMB = ((f.size || 0) / 1024).toFixed(1);
      console.log(`     - ${f.name} (${sizeMB} KB, ${f.lastModifiedDateTime || 'unknown'})`);
    }
    if (files.length > 5) console.log(`     ... and ${files.length - 5} more`);
    assert(filesRes.ok, 'File listing succeeded');
  } else {
    console.log('\n6. Skipping file listing (no folders tracked)');
  }

  // ── 7. Get file metadata ──
  if (uploadedItemId) {
    console.log(`\n7. Getting metadata for uploaded file...`);
    const metaRes = await request('GET', `/sharepoint/files/${uploadedItemId}/metadata`);
    if (metaRes.ok) {
      console.log(`   Name: ${metaRes.data?.data?.name}`);
      console.log(`   Size: ${metaRes.data?.data?.size} bytes`);
      assert(true, 'File metadata retrieved');
    }
  } else {
    console.log('\n7. Skipping metadata check (no file uploaded)');
  }

  // ── 8. Download file ──
  if (uploadedItemId) {
    console.log(`\n8. Downloading file...`);
    const dlRes = await fetch(`${API_BASE}/sharepoint/files/${uploadedItemId}/download`, {
      headers: { 'X-API-Key': API_KEY },
    });
    if (dlRes.ok) {
      const content = await dlRes.text();
      console.log(`   Downloaded ${content.length} bytes`);
      assert(content.includes('Test Document'), 'Downloaded content matches');
    } else {
      console.log(`   Download failed: ${dlRes.status}`);
    }
  } else {
    console.log('\n8. Skipping download (no file uploaded)');
  }

  // ── 9. Search files ──
  console.log('\n9. Searching for files...');
  const searchRes = await request('GET', '/sharepoint/search?q=velo');
  if (searchRes.ok) {
    const results = searchRes.data?.data || [];
    console.log(`   Search results: ${results.length}`);
    assert(true, 'Search completed');
  }

  // ── 10. Delete test file ──
  if (uploadedItemId) {
    console.log(`\n10. Deleting test file...`);
    const delRes = await request('DELETE', `/sharepoint/files/${uploadedItemId}`);
    if (delRes.ok) {
      assert(true, 'File deleted successfully');
    } else {
      console.log(`   Delete status: ${delRes.status}`);
    }
  } else {
    console.log('\n10. Skipping delete (no file uploaded)');
  }

  // ── 11. Run SharePoint audit ──
  console.log('\n11. Running SharePoint content audit...');
  const auditRes = await request('POST', `/sharepoint/projects/${projectId}/audit`, {});
  if (auditRes.ok) {
    const auditId = auditRes.data?.data?.auditId;
    console.log(`   Audit started: ${auditId}`);
    assert(!!auditId, 'Audit ID returned');

    // Wait a moment for async processing
    await new Promise(r => setTimeout(r, 3000));

    // Check audit status
    const checkRes = await request('GET', `/projects/${projectId}`);
    if (checkRes.ok) {
      const audits = checkRes.data?.data?.audits || [];
      const spAudit = audits.find((a: any) => a.pk_project_audit === auditId);
      if (spAudit) {
        console.log(`   Audit status: ${spAudit.audit_status}`);
      }
    }
  } else {
    console.log(`   Audit start failed: ${auditRes.status}`);
  }

  // ── Summary ──
  console.log('\n═══════════════════════════════════════════════════');
  console.log('SharePoint E2E Test Complete');
  console.log('═══════════════════════════════════════════════════');
}

main().catch((err) => {
  console.error('Test failed:', err);
  process.exitCode = 1;
});
