#!/usr/bin/env node
/**
 * build-readme.mjs
 *
 * Replaces auto-generated sections in README.md with current data.
 * Idempotent: running twice produces the same output as running once.
 *
 * Markers (placed in README.md):
 *   <!-- AUTOGENERATED:migrations-count -->NN<!-- /AUTOGENERATED:migrations-count -->
 *   <!-- AUTOGENERATED:openapi-version -->X.Y.Z<!-- /AUTOGENERATED:openapi-version -->
 *
 * The script finds each marker pair and replaces only the content between them,
 * leaving the rest of README.md untouched.
 *
 * Run: npm run build:readme
 *
 * Once these markers are added to the README, the migration count and openapi
 * version will be kept in lock-step with the codebase by re-running this script
 * (and check-docs-sync.mjs will catch any divergence even if you forget).
 */

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(__dirname, '..');
const README   = path.join(APP_ROOT, 'README.md');
const MIGRATIONS = path.join(APP_ROOT, 'server/migrations');
const OPENAPI    = path.join(APP_ROOT, 'server/openapi.yaml');

if (!fs.existsSync(README)) {
  console.error('README.md not found at', README);
  process.exit(1);
}

let text = fs.readFileSync(README, 'utf8');
const replacements = [];

// 1. Migration count
{
  const count = fs.readdirSync(MIGRATIONS)
    .filter(f => /^\d{3}_.*\.sql$/.test(f))
    .length;
  text = replaceMarker(text, 'migrations-count', String(count), replacements);
}

// 2. OpenAPI version
{
  const oapi = fs.readFileSync(OPENAPI, 'utf8');
  const m = oapi.match(/^\s*version:\s*(\d+\.\d+\.\d+)/m);
  if (m) text = replaceMarker(text, 'openapi-version', m[1], replacements);
}

if (replacements.length === 0) {
  console.log('build-readme: no markers found in README.md.');
  console.log('Add markers like:');
  console.log('  <!-- AUTOGENERATED:migrations-count -->63<!-- /AUTOGENERATED:migrations-count -->');
  console.log('to the relevant sections, then re-run.');
  process.exit(0);
}

fs.writeFileSync(README, text);
console.log(`build-readme: updated ${replacements.length} marker section(s):`);
for (const r of replacements) {
  console.log(`  • ${r.name} → ${r.value}${r.changed ? ' (CHANGED)' : ' (unchanged)'}`);
}

// ---------------------------------------------------------------------------
function replaceMarker(text, name, newValue, replacements) {
  const re = new RegExp(
    `<!--\\s*AUTOGENERATED:${name}\\s*-->([\\s\\S]*?)<!--\\s*/AUTOGENERATED:${name}\\s*-->`,
    'g',
  );
  let found = false;
  const replaced = text.replace(re, (_, currentValue) => {
    found = true;
    const changed = currentValue.trim() !== newValue.trim();
    replacements.push({ name, value: newValue, changed });
    return `<!-- AUTOGENERATED:${name} -->${newValue}<!-- /AUTOGENERATED:${name} -->`;
  });
  if (!found) console.warn(`build-readme: marker '${name}' not present in README — skipped.`);
  return replaced;
}
