/**
 * Generate and update ALL cryptographic secrets for Velo.
 * One-stop shop — handles both symmetric secrets (.env) and asymmetric keys (PEM files).
 *
 * Usage:
 *   npm run generate-secrets              # Generate missing secrets + keys, skip existing
 *   npm run generate-secrets -- --force   # Regenerate ALL (overwrites existing)
 *   npm run generate-secrets -- --check   # Audit current secret strength
 *   npm run generate-secrets -- --print   # Print new values without writing
 *
 * Part 1 — Symmetric Secrets (written to .env):
 *   ENCRYPTION_KEY       — AES-256-CBC key (32 bytes hex = 64 chars) for encrypting PATs
 *   CSRF_SECRET          — HMAC-SHA256 key (48 bytes hex = 96 chars) for CSRF tokens
 *
 * Part 2 — Asymmetric RSA-2048 Key Pairs (written to server/keys/):
 *   jwt-private.pem / jwt-public.pem                 — Sign/verify access tokens
 *   jwt-refresh-private.pem / jwt-refresh-public.pem — Sign/verify refresh tokens
 *
 * How JWT keys are loaded at runtime (see utils/token.ts):
 *   1. Check server/keys/*.pem files on disk ← Development (generated by this script)
 *   2. Fallback to .env vars: JWT_PRIVATE_KEY, JWT_PUBLIC_KEY, etc. ← Production (Azure Key Vault)
 *   3. If neither exists → server crashes at startup with a clear error
 *
 * Requirements (from environment.ts Zod schema):
 *   ENCRYPTION_KEY: z.string().min(16)  — we generate 64 chars (32 bytes) for AES-256
 *   CSRF_SECRET:    z.string().min(32)  — we generate 96 chars (48 bytes) for HMAC-SHA256
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

const ENV_PATH = path.resolve(__dirname, '..', '..', '.env');
const KEYS_DIR = path.resolve(__dirname, '..', '..', 'keys');

// ---------------------------------------------------------------------------
// Secret definitions
// ---------------------------------------------------------------------------

interface SecretDef {
  name: string;
  envVar: string;
  bytes: number;         // random bytes to generate
  format: 'hex' | 'base64';
  description: string;
  minLength: number;     // from Zod schema
  isInsecure: (val: string) => boolean; // detect dev defaults
}

const SECRETS: SecretDef[] = [
  {
    name: 'Encryption Key (AES-256)',
    envVar: 'ENCRYPTION_KEY',
    bytes: 32,           // 32 bytes = 256 bits for AES-256
    format: 'hex',       // 64 hex chars
    description: 'Used for AES-256-CBC encryption of sensitive data (GitHub PATs)',
    minLength: 16,
    isInsecure: (v) => v.includes('dev') || v.includes('change') || v.includes('default') || v.length < 32,
  },
  {
    name: 'CSRF Secret (HMAC-SHA256)',
    envVar: 'CSRF_SECRET',
    bytes: 48,           // 48 bytes = 96 hex chars, well above 32 min
    format: 'hex',
    description: 'Used for HMAC-SHA256 signing of CSRF double-submit tokens',
    minLength: 32,
    isInsecure: (v) => v.includes('dev') || v.includes('change') || v.includes('default') || v.length < 48,
  },
];

// ---------------------------------------------------------------------------
// Secret generation
// ---------------------------------------------------------------------------

function generateSecret(def: SecretDef): string {
  const bytes = crypto.randomBytes(def.bytes);
  return def.format === 'hex' ? bytes.toString('hex') : bytes.toString('base64url');
}

function assessStrength(value: string, def: SecretDef): { ok: boolean; reason: string } {
  if (!value || value.length === 0) return { ok: false, reason: 'missing' };
  if (value.length < def.minLength) return { ok: false, reason: `too short (${value.length} < ${def.minLength})` };
  if (def.isInsecure(value)) return { ok: false, reason: 'insecure default value' };

  // Check entropy — hex strings only have 16 possible chars, so check bit strength instead
  const isHex = /^[0-9a-f]+$/i.test(value);
  const bitsOfEntropy = isHex ? value.length * 4 : value.length * 6; // hex=4 bits/char, base64≈6
  if (bitsOfEntropy < 128) return { ok: false, reason: `weak entropy (~${bitsOfEntropy} bits, need 128+)` };

  return { ok: true, reason: `${value.length} chars, ~${bitsOfEntropy} bits of entropy` };
}

// ---------------------------------------------------------------------------
// .env file operations
// ---------------------------------------------------------------------------

function readEnv(): Map<string, string> {
  const env = new Map<string, string>();
  if (!fs.existsSync(ENV_PATH)) return env;

  const content = fs.readFileSync(ENV_PATH, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.substring(0, eqIdx).trim();
    let value = trimmed.substring(eqIdx + 1).trim();
    // Strip surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env.set(key, value);
  }
  return env;
}

function updateEnvFile(updates: Map<string, string>): void {
  let content = '';
  if (fs.existsSync(ENV_PATH)) {
    content = fs.readFileSync(ENV_PATH, 'utf-8');
  }

  for (const [key, value] of updates) {
    // Check if key already exists in file
    const regex = new RegExp(`^${key}\\s*=.*$`, 'm');
    const newLine = `${key}=${value}`;

    if (regex.test(content)) {
      // Replace existing line
      content = content.replace(regex, newLine);
    } else {
      // Append to end
      if (!content.endsWith('\n') && content.length > 0) content += '\n';
      content += `${newLine}\n`;
    }
  }

  fs.writeFileSync(ENV_PATH, content);
}

// ---------------------------------------------------------------------------
// CLI commands
// ---------------------------------------------------------------------------

function check(): void {
  console.log('Checking existing secrets...\n');
  const env = readEnv();
  let allOk = true;

  for (const def of SECRETS) {
    const value = env.get(def.envVar) || '';
    const assessment = assessStrength(value, def);
    const icon = assessment.ok ? '\x1b[32m[OK]\x1b[0m' : '\x1b[31m[!!]\x1b[0m';
    console.log(`  ${icon} ${def.envVar}`);
    console.log(`       ${assessment.reason}`);
    console.log(`       ${def.description}`);
    if (!assessment.ok) allOk = false;
  }

  // Check RSA keys
  checkRSAKeys();

  console.log('');
  if (allOk) {
    console.log('\x1b[32mAll secrets are production-ready.\x1b[0m');
  } else {
    console.log('\x1b[31mSome secrets need attention. Run: npm run generate-secrets\x1b[0m');
    process.exitCode = 1;
  }
}

function generate(force: boolean, printOnly: boolean): void {
  console.log(force ? 'Regenerating ALL secrets...\n' : 'Generating missing/insecure secrets...\n');

  const env = readEnv();
  const updates = new Map<string, string>();

  for (const def of SECRETS) {
    const existing = env.get(def.envVar) || '';
    const assessment = assessStrength(existing, def);

    if (!force && assessment.ok) {
      console.log(`  [skip] ${def.envVar} — already secure (${assessment.reason})`);
      continue;
    }

    const newValue = generateSecret(def);
    updates.set(def.envVar, newValue);

    const reason = !existing ? 'missing' : force ? 'forced regeneration' : assessment.reason;
    console.log(`  [new]  ${def.envVar} — ${newValue.length} chars (${reason})`);

    if (printOnly) {
      console.log(`         ${def.envVar}=${newValue}`);
    }
  }

  if (updates.size === 0) {
    console.log('\nAll secrets are already secure. Use --force to regenerate.');
    return;
  }

  if (printOnly) {
    console.log('\n(--print mode: secrets not written to .env)');
    return;
  }

  updateEnvFile(updates);
  console.log(`\n\x1b[32mUpdated ${updates.size} secret(s) in ${ENV_PATH}\x1b[0m`);

  // Also ensure RSA key pairs exist
  ensureRSAKeys(force);

  console.log('\nRestart the server for changes to take effect.');
}

// ---------------------------------------------------------------------------
// RSA Key Pair Generation (JWT RS256)
// ---------------------------------------------------------------------------

const KEY_PAIRS = [
  { name: 'Access Token',  privateFile: 'jwt-private.pem',         publicFile: 'jwt-public.pem',         envPrivate: 'JWT_PRIVATE_KEY',         envPublic: 'JWT_PUBLIC_KEY' },
  { name: 'Refresh Token', privateFile: 'jwt-refresh-private.pem', publicFile: 'jwt-refresh-public.pem', envPrivate: 'JWT_REFRESH_PRIVATE_KEY', envPublic: 'JWT_REFRESH_PUBLIC_KEY' },
];

function ensureRSAKeys(force: boolean): void {
  console.log('\n── RSA-2048 Key Pairs (RS256 JWT Signing) ──\n');

  if (!fs.existsSync(KEYS_DIR)) {
    fs.mkdirSync(KEYS_DIR, { recursive: true });
  }

  for (const pair of KEY_PAIRS) {
    const privatePath = path.join(KEYS_DIR, pair.privateFile);
    const publicPath = path.join(KEYS_DIR, pair.publicFile);
    const exists = fs.existsSync(privatePath) && fs.existsSync(publicPath);

    if (exists && !force) {
      console.log(`  [skip] ${pair.name}: ${pair.privateFile} + ${pair.publicFile} (already exist)`);
      continue;
    }

    const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
      modulusLength: 2048,
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    });

    fs.writeFileSync(privatePath, privateKey, { mode: 0o600 });
    fs.writeFileSync(publicPath, publicKey, { mode: 0o644 });
    console.log(`  [new]  ${pair.name}: ${pair.privateFile} + ${pair.publicFile} (RSA-2048)`);
  }

  console.log(`\n  PEM files stored in: ${KEYS_DIR}`);
  console.log('  These files are gitignored. Do NOT commit them.');
  console.log('  For production: inject PEM contents as env vars via Azure Key Vault.');
  console.log(`    Fallback env vars: ${KEY_PAIRS.map(p => p.envPrivate).join(', ')}`);
}

function checkRSAKeys(): void {
  console.log('\n── RSA Key Pairs ──\n');
  for (const pair of KEY_PAIRS) {
    const privatePath = path.join(KEYS_DIR, pair.privateFile);
    const publicPath = path.join(KEYS_DIR, pair.publicFile);
    const privateExists = fs.existsSync(privatePath);
    const publicExists = fs.existsSync(publicPath);

    if (!privateExists || !publicExists) {
      console.log(`  \x1b[31m[!!]\x1b[0m ${pair.name}: ${!privateExists ? pair.privateFile + ' missing' : ''}${!privateExists && !publicExists ? ', ' : ''}${!publicExists ? pair.publicFile + ' missing' : ''}`);
      continue;
    }

    // Verify sign+verify roundtrip
    try {
      const privateKey = fs.readFileSync(privatePath, 'utf-8');
      const publicKey = fs.readFileSync(publicPath, 'utf-8');
      const data = 'test-' + Date.now();
      const signature = crypto.sign('sha256', Buffer.from(data), privateKey);
      const verified = crypto.verify('sha256', Buffer.from(data), publicKey, signature);
      if (verified) {
        console.log(`  \x1b[32m[OK]\x1b[0m ${pair.name}: sign+verify OK (RSA-2048)`);
      } else {
        console.log(`  \x1b[31m[!!]\x1b[0m ${pair.name}: sign+verify FAILED`);
      }
    } catch (err) {
      console.log(`  \x1b[31m[!!]\x1b[0m ${pair.name}: ${(err as Error).message}`);
    }
  }
}

// ---------------------------------------------------------------------------
// CLI entry
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

console.log('Velo Secret Generator\n');
console.log(`  .env path: ${ENV_PATH}`);
console.log(`  keys path: ${KEYS_DIR}\n`);

if (args.includes('--check')) {
  check();
} else if (args.includes('--print')) {
  generate(args.includes('--force'), true);
} else {
  generate(args.includes('--force'), false);
}
